### ISSUE TITLE
US/Pacificが使えない

### ISSUE THREAD

**Issue by Kouki-glow** [oss-experiment-uec/2024-t2210419-arrow#1]
## Issue Description

local = utc.to('US/Pacific')を実行した際に
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/arrow/arrow.py", line 1077, in to
    tz = parser.TzinfoParser.parse(tz)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/arrow/parser.py", line 777, in parse
    raise ParserError(f"Could not parse timezone expression {tzinfo_string!r}.")
arrow.parser.ParserError: Could not parse timezone expression 'US/Pacific'.
というエラーメッセージが出力された.
local = utc.to('utc')とすると以下のコマンドも含めて問題なく出力された.

## System Info

- 🖥  **OS name and version**: macOS Sonoma 14.5
- 🐍  **Python version**:Python 3.12.3

**Comment by ryota2357** [comment]
同じくエラーになりました。

OS: macOS 15.1 (x86_64)
